#
# .bash_aliases
#
alias less='less -M'
alias f='finger'
alias ls='ls -CF'
alias ll='ls -l'
alias la='ls -a'
alias lal='ls -al'
alias lcap='ls [A-Z]*'
alias rm='rm -i'
alias r='resize'
alias m='less -M'
alias more='less -M'
alias h='history'
alias c='/usr/bin/clear'
alias d='date +"%n%t%D %a%n%t%r%n"'
alias land='enscript -2rhGj'
alias psv='ps -ef | grep -v root'
alias psef='ps -ef | grep -i screen | grep -v grep ; ps -ef | grep -i tmux | grep -v grep'
alias lnew='ls -alt | head -16'
alias lrt='ls -alrt'
alias su='su -m'
alias whatami='lsb-release -a'
alias wai='lsb-release -a'
alias nver='cat /proc/driver/nvidia/version'
alias sti='sudo tripwire --check --interactive'
alias ml='last -2000 | grep -v root | head -20'
